name: API 28 image build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: actions/checkout@v3

      - name: Get apk tools
        run: |
          curl -LO http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/aarch64/apk-tools-static-2.12.10-r1.apk
          tar -xzf apk-tools-static-*.apk

      - name: Setup minimal Alpine chroot
        run: |
          mkdir alpine-chroot
          sudo ./sbin/apk.static -X http://dl-cdn.alpinelinux.org/alpine/v3.17/main -U --allow-untrusted -p alpine-chroot/ --initdb add alpine-base
          sudo mkdir -p alpine-chroot/etc/apk
          echo "http://dl-cdn.alpinelinux.org/alpine/v3.17/main" | sudo tee -a alpine-chroot/etc/apk/repositories
          echo "http://dl-cdn.alpinelinux.org/alpine/v3.17/community" | sudo tee -a alpine-chroot/etc/apk/repositories
          echo "http://mirror.bardia.tech/alphybris" | sudo tee -a alpine-chroot/etc/apk/repositories
          sudo mount -o bind /dev alpine-chroot/dev
          sudo mount -t proc none alpine-chroot/proc
          sudo mount -o bind /sys alpine-chroot/sys
          echo -e 'nameserver 8.8.8.8\nnameserver 2620:0:ccc::2' | sudo tee alpine-chroot/etc/resolv.conf

      - name: Install AlpHybris base
        run: |
          sudo chroot alpine-chroot/ /bin/ash -c "/usr/bin/wget -P /etc/apk/keys https://mirror.bardia.tech/alphybris/aarch64/fakeshell@bardia.tech-642c0d85.rsa.pub"
          sudo chroot alpine-chroot/ /bin/ash -c "/sbin/apk update"
          sudo chroot alpine-chroot/ /bin/ash -c "/sbin/rc-update add devfs sysinit && /sbin/rc-update add dmesg sysinit && /sbin/rc-update add mdev sysinit && /sbin/rc-update add hwclock boot && /sbin/rc-update add modules boot && /sbin/rc-update add sysctl boot && /sbin/rc-update add hostname boot && /sbin/rc-update add bootmisc boot && /sbin/rc-update add syslog boot && /sbin/rc-update add mount-ro shutdown && /sbin/rc-update add killprocs shutdown && /sbin/rc-update add savecache shutdown"
          sudo chroot alpine-chroot/ /bin/ash -c "/sbin/apk add sudo && echo '%wheel ALL=(ALL) ALL' | tee /etc/sudoers.d/wheel"
          sudo chroot alpine-chroot/ /bin/ash -c "/usr/sbin/adduser -D -u 32011 alphybris"
          sudo chroot alpine-chroot/ /bin/ash -c "/usr/sbin/adduser alphybris wheel"
          sudo chroot alpine-chroot/ /bin/ash -c "/sbin/apk add alphybris-base-api28"

      - name: Pack up rootfs
        run: |
          sudo bash ./pack-rootfs
